### ISSUE TITLE
Fails to run on Python 3.5

### ISSUE THREAD

**Issue by kseistrup** [toxinu/pyhn#36]
I'm aware that `pyhn` is not listed on PyPI as being run on Python 3.5. However, Python 3.5 is the current default Python version and it is the version that provides the Python interpreter on e.g. ArchLinux, so it would be sweet to have `pyhn` running on Python 3.5.
```pytb
$ pyhn
Traceback (most recent call last):
  File "/usr/bin/pyhn", line 4, in <module>
    from pyhn.cachemanager import CacheManager
  File "/usr/lib/python3.5/site-packages/pyhn/cachemanager.py", line 7, in <module>
    from pyhn.hnapi import HackerNewsAPI
  File "/usr/lib/python3.5/site-packages/pyhn/hnapi.py", line 49, in <module>
    from pyhn.lib.bs4_py3 import BeautifulSoup
  File "/usr/lib/python3.5/site-packages/pyhn/lib/bs4_py3/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3.5/site-packages/pyhn/lib/bs4_py3/builder/__init__.py", line 308, in <module>
    from . import _htmlparser
  File "/usr/lib/python3.5/site-packages/pyhn/lib/bs4_py3/builder/_htmlparser.py", line 7, in <module>
    from html.parser import (
ImportError: cannot import name 'HTMLParseError'
$
```

**Comment by toxinu** [comment]
Thank you for reporting this bug @kseistrup. :smile: 
I just fixed it and published a new release on pypi.

You just have to run `pip install -U pyhn` to update it.
